apiVersion: apps/v1
kind: Deployment
metadata:
  name: register-app-deployment
  namespace: register-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: register-app
  template:
    metadata:
      labels:
        app: register-app
    spec:
      containers:
        - name: register-app
          image: muthukumar001/register-app-pipeline:1.0.0-244
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080
